name: stock_watchlist
description: "An app that lets you choose any financial instrument to a watch list and track their prices real time"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  awesome_dio_interceptor: ^1.1.0
  dio: ^5.4.1
  flutter_riverpod: ^3.0.0-dev.3
  freezed_annotation: ^2.4.1
  http: ^1.2.0
  json_annotation: ^4.8.1
  google_fonts: ^6.1.0
  neumorphic_ui: ^1.0.1
  riverpod_annotation: ^3.0.0-dev.3
  shared_preferences: ^2.2.2




  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  custom_lint: ^0.5.2
  flutter_lints: ^3.0.1
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  localstore: ^1.3.5
  riverpod_generator: ^3.0.0-dev.11
  riverpod_lint: ^3.0.0-dev.4
  system_theme: ^2.3.1


flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
