import 'package:flutter/material.dart';

import 'texts.dart';

ThemeData getDarkTheme() => ThemeData(
      useMaterial3: true,
      brightness: Brightness.dark,
      scaffoldBackgroundColor: const Color(0xff292d32),
      colorScheme: const ColorScheme.dark(
        brightness: Brightness.dark,
        background: Color(0xff292d32),
        onBackground: Color(0xffefeeee),
        primary: Color(0xFF9272FF),
        secondary: Color(0xFF64FAC3),
        tertiary: Color(0xFFFF5180),
        primaryContainer: Color(0xff292d32),
        onPrimaryContainer: Color(0xffefeeee),
        secondaryContainer: Color(0xff393053),
        tertiaryContainer: Color(0xff18122b),
        outline: Color(0xffefeeee),
        outlineVariant: Color(0xffF8E8EE),
        // onPrimary: ,
        // onSecondary: ,
        // onSecondaryContainer: ,
        // onTertiary: ,
        // onTertiaryContainer: ,
        // error: Color(0xFFFF5180),
        // onError: ,
        // errorContainer: Color(0xFFf04a63),
        // onErrorContainer: ,
        // surface: ,
        // onSurface: ,
        // surfaceTint: ,
        // onSurfaceVariant: ,
      ),
      // Text
      textTheme: textThemeDark,
      iconTheme: const IconThemeData(color: Color(0xffefeeee)),
    );

ThemeData getLightTheme() => ThemeData(
      useMaterial3: true,
      brightness: Brightness.light,
      scaffoldBackgroundColor: const Color(0xffefeeee),
      colorScheme: const ColorScheme.light(
        brightness: Brightness.light,
        background: Color(0xffefeeee),
        onBackground: Color(0xff292d32),
        primary: Color(0xFF9272FF),
        secondary: Color(0xFF64FAC3),
        tertiary: Color(0xFFFF5180),
        primaryContainer: Color(0xffefeeee),
        onPrimaryContainer: Color(0xff292d32),
        secondaryContainer: Color(0xffc9e4de),
        tertiaryContainer: Color(0xfff7d9c4),
        outline: Color(0xff635985),
        outlineVariant: Color(0xff443c68),
        // onPrimary: ,
        // onSecondary: ,
        // onSecondaryContainer: ,
        // onTertiary: ,
        // onTertiaryContainer: ,
        // error: Color(0xFFFF5180),
        // onError: ,
        // errorContainer: Color(0xFFf04a63),
        // onErrorContainer: ,
        // surface: ,
        // onSurface: ,
        // surfaceTint: ,
        // onSurfaceVariant: ,
      ),
      textTheme: textThemeLight,
      iconTheme: const IconThemeData(color: Color(0xff292d32)),
    );
